// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: prt.proto

package protof

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author    []string `protobuf:"bytes,2,rep,name=author,proto3" json:"author,omitempty"`
	ShortDesc string   `protobuf:"bytes,3,opt,name=short_desc,json=shortDesc,proto3" json:"short_desc,omitempty"`
	BookId    int64    `protobuf:"varint,4,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_prt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_prt_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetAuthor() []string {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Book) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

func (x *Book) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type Lim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	L int64 `protobuf:"varint,1,opt,name=l,proto3" json:"l,omitempty"`
}

func (x *Lim) Reset() {
	*x = Lim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lim) ProtoMessage() {}

func (x *Lim) ProtoReflect() protoreflect.Message {
	mi := &file_prt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lim.ProtoReflect.Descriptor instead.
func (*Lim) Descriptor() ([]byte, []int) {
	return file_prt_proto_rawDescGZIP(), []int{1}
}

func (x *Lim) GetL() int64 {
	if x != nil {
		return x.L
	}
	return 0
}

type Dispbook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookList []*Book `protobuf:"bytes,1,rep,name=book_list,json=bookList,proto3" json:"book_list,omitempty"`
	Ak       *Ack    `protobuf:"bytes,2,opt,name=ak,proto3" json:"ak,omitempty"`
}

func (x *Dispbook) Reset() {
	*x = Dispbook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dispbook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dispbook) ProtoMessage() {}

func (x *Dispbook) ProtoReflect() protoreflect.Message {
	mi := &file_prt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dispbook.ProtoReflect.Descriptor instead.
func (*Dispbook) Descriptor() ([]byte, []int) {
	return file_prt_proto_rawDescGZIP(), []int{2}
}

func (x *Dispbook) GetBookList() []*Book {
	if x != nil {
		return x.BookList
	}
	return nil
}

func (x *Dispbook) GetAk() *Ack {
	if x != nil {
		return x.Ak
	}
	return nil
}

type Review struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId int64  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score  int64  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Text   string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Review) Reset() {
	*x = Review{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_prt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_prt_proto_rawDescGZIP(), []int{3}
}

func (x *Review) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *Review) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Review) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Review) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Rv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId int64 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
}

func (x *Rv) Reset() {
	*x = Rv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rv) ProtoMessage() {}

func (x *Rv) ProtoReflect() protoreflect.Message {
	mi := &file_prt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rv.ProtoReflect.Descriptor instead.
func (*Rv) Descriptor() ([]byte, []int) {
	return file_prt_proto_rawDescGZIP(), []int{4}
}

func (x *Rv) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type Dispreview struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReviewList []*Review `protobuf:"bytes,1,rep,name=review_list,json=reviewList,proto3" json:"review_list,omitempty"`
	Ak         *Ack      `protobuf:"bytes,2,opt,name=ak,proto3" json:"ak,omitempty"`
}

func (x *Dispreview) Reset() {
	*x = Dispreview{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dispreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dispreview) ProtoMessage() {}

func (x *Dispreview) ProtoReflect() protoreflect.Message {
	mi := &file_prt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dispreview.ProtoReflect.Descriptor instead.
func (*Dispreview) Descriptor() ([]byte, []int) {
	return file_prt_proto_rawDescGZIP(), []int{5}
}

func (x *Dispreview) GetReviewList() []*Review {
	if x != nil {
		return x.ReviewList
	}
	return nil
}

func (x *Dispreview) GetAk() *Ack {
	if x != nil {
		return x.Ak
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_prt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_prt_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Ack) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_prt_proto protoreflect.FileDescriptor

var file_prt_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x66, 0x22, 0x6a, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22,
	0x13, 0x0a, 0x03, 0x6c, 0x69, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x01, 0x6c, 0x22, 0x52, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x70, 0x62, 0x6f, 0x6f, 0x6b,
	0x12, 0x29, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x02, 0x61,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66,
	0x2e, 0x61, 0x63, 0x6b, 0x52, 0x02, 0x61, 0x6b, 0x22, 0x5f, 0x0a, 0x06, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x1d, 0x0a, 0x02, 0x72, 0x76, 0x12,
	0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x70,
	0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x2f, 0x0a, 0x0b, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x66, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x0a, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x02, 0x61, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x2e, 0x61, 0x63, 0x6b,
	0x52, 0x02, 0x61, 0x6b, 0x22, 0x2f, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xb8, 0x01, 0x0a, 0x03, 0x53, 0x52, 0x56, 0x12, 0x2b, 0x0a,
	0x08, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x66, 0x2e, 0x6c, 0x69, 0x6d, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x2e,
	0x64, 0x69, 0x73, 0x70, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x08, 0x69, 0x6e,
	0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x2e, 0x61, 0x63,
	0x6b, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x2e, 0x61, 0x63, 0x6b, 0x22, 0x00,
	0x12, 0x2e, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x0a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x2e, 0x72, 0x76, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x66, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x22, 0x00,
	0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prt_proto_rawDescOnce sync.Once
	file_prt_proto_rawDescData = file_prt_proto_rawDesc
)

func file_prt_proto_rawDescGZIP() []byte {
	file_prt_proto_rawDescOnce.Do(func() {
		file_prt_proto_rawDescData = protoimpl.X.CompressGZIP(file_prt_proto_rawDescData)
	})
	return file_prt_proto_rawDescData
}

var file_prt_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_prt_proto_goTypes = []interface{}{
	(*Book)(nil),       // 0: protof.book
	(*Lim)(nil),        // 1: protof.lim
	(*Dispbook)(nil),   // 2: protof.dispbook
	(*Review)(nil),     // 3: protof.review
	(*Rv)(nil),         // 4: protof.rv
	(*Dispreview)(nil), // 5: protof.dispreview
	(*Ack)(nil),        // 6: protof.ack
}
var file_prt_proto_depIdxs = []int32{
	0, // 0: protof.dispbook.book_list:type_name -> protof.book
	6, // 1: protof.dispbook.ak:type_name -> protof.ack
	3, // 2: protof.dispreview.review_list:type_name -> protof.review
	6, // 3: protof.dispreview.ak:type_name -> protof.ack
	1, // 4: protof.SRV.get_book:input_type -> protof.lim
	0, // 5: protof.SRV.ins_book:input_type -> protof.book
	3, // 6: protof.SRV.ins_review:input_type -> protof.review
	4, // 7: protof.SRV.get_review:input_type -> protof.rv
	2, // 8: protof.SRV.get_book:output_type -> protof.dispbook
	6, // 9: protof.SRV.ins_book:output_type -> protof.ack
	6, // 10: protof.SRV.ins_review:output_type -> protof.ack
	5, // 11: protof.SRV.get_review:output_type -> protof.dispreview
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_prt_proto_init() }
func file_prt_proto_init() {
	if File_prt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dispbook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Review); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dispreview); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prt_proto_goTypes,
		DependencyIndexes: file_prt_proto_depIdxs,
		MessageInfos:      file_prt_proto_msgTypes,
	}.Build()
	File_prt_proto = out.File
	file_prt_proto_rawDesc = nil
	file_prt_proto_goTypes = nil
	file_prt_proto_depIdxs = nil
}
